development:
  adapter: mysql
  encoding: utf8
  database: compreingressos_development
  username: root
  password: 123
  pool: 20
  timeout: 50000
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: compreingressos_development
  username: root
  password: 123
  pool: 20
  timeout: 50000
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: compreingressos_production
  username: php
  password: SNq3mhh5Tyb59J
  pool: 100
  timeout: 50000
  host: 192.168.81.15,4003

staging:
  adapter: mysql
  encoding: utf8
  database: compreingressos_staging
  username: root
  password: 123
  pool: 100
  timeout: 50000
  host: localhost
