# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen

theme: advanced
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_resizing: true
theme_advanced_resize_horizontal: true
theme_advanced_blockformats: p,h5,h6
content_css: '/stylesheets/ci.css'
theme_advanced_buttons1: formatselect, bold, italic, underline, separator, indent, outdent, separator, bullist, numlist, separator, link, unlink, undo, redo
theme_advanced_buttons2: [] 
#  :theme_advanced_buttons3 => [],
#plugins: contextmenu, paste
#plugins: contextmenu
#paste_remove_styles: true
#:paste_auto_cleanup_on_paste => true,
#only: :new, :edit,:create]
